[versions]
mockk = "1.13.2"
compose = "1.3.0-rc01"
composeMaterial = "1.3.1"
kotlinCompiler = "1.3.2"
navigationCompose = "2.5.2"
junit = "4.13.2"
testng = "6.9.6"
androidJunit = "1.1.4"
espresso = "3.5.0"
androidCore = "1.9.0"
lifeCycle = "2.5.1"
composeActivity = "1.6.1"
viewModel = "2.5.1"
dagger = "2.44"
coroutines = "1.6.1"
cameraX = "1.3.0-alpha01"
retrofit = "2.9.0"
okHttp = "4.11.0"
workManager = "2.7.1"
instrumentalTest = "1.5.0"
testRunner = "1.5.1"
jUnitKtx = "1.1.4"
coil = "2.2.2"
moshi = "1.13.0"
dataStore = "1.0.0"
room = "2.5.0"
permissions = "0.26.2-beta"
biometric = "1.2.0-alpha05"
fragment = "1.5.5"
appCompat = "1.6.0"
adMob = "21.4.0"
billing = "5.1.0"
materialDialogs = "0.9.0"
immutableCollections = "0.3.5"
desugar = "2.0.2"
firebaseBom = "31.1.1"
googleServices = "4.3.15"
firebaseCrashlyticsPlugin = "2.9.4"
guardsquare = "latest.release"
androidGradlePlugin = "8.13.1"
kotlin = "2.2.21"

[libraries]
# Desugar
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }

# Compose
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
compose-test-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-test-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
compose-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "compose" }

# Test
junit = { module = "junit:junit", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
testng = { module = "org.testng:testng", version.ref = "testng" }

# TestAndroid
android-junit = { module = "androidx.test.ext:junit", version.ref = "androidJunit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }

# AndroidX
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidCore" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifeCycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }

# ViewModel
viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "viewModel" }
viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "viewModel" }

# Dagger
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

# Coroutines
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# CameraX
camerax-core = { module = "androidx.camera:camera-core", version.ref = "cameraX" }
camerax-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraX" }
camerax-extensions = { module = "androidx.camera:camera-extensions", version.ref = "cameraX" }
camerax-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraX" }

# Retrofit2
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okHttp" }

# WorkManager
workmanager = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
workmanager-testing = { module = "androidx.work:work-testing", version.ref = "workManager" }

# InstrumentalTest
instrumental-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
instrumental-test-runner = { module = "androidx.test:runner", version.ref = "testRunner" }
instrumental-test-core = { module = "androidx.test:core", version.ref = "instrumentalTest" }
instrumental-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "jUnitKtx" }
instrumental-test-rules = { module = "androidx.test:rules", version.ref = "instrumentalTest" }

# Coil
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

# Moshi
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

# DataStore
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

# Permissions
permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "permissions" }

# Biometric
biometric = { module = "androidx.biometric:biometric-ktx", version.ref = "biometric" }

# Fragment
fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }

# AppCompat
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appCompat" }

# AdMob
admob = { module = "com.google.android.gms:play-services-ads", version.ref = "adMob" }

# Billing
billing = { module = "com.android.billingclient:billing-ktx", version.ref = "billing" }

# MaterialDialog
material-dialogs = { module = "io.github.vanpra.compose-material-dialogs:datetime", version.ref = "materialDialogs" }

# ImmutableCollection
immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "immutableCollections" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }

[plugins]
dagger-kapt = { id = "kotlin-kapt" }
moshi-kapt = { id = "com.squareup.moshi.kapt" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
guardsquare = { id = "com.guardsquare.appsweep", version.ref = "guardsquare" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]
compose = ["compose-ui", "compose-tooling", "compose-material"]
test = ["junit", "mockk", "testng"]
android-test = ["android-junit", "espresso-core", "mockk-android", "mockk-agent"]
androidx = ["androidx-core", "androidx-lifecycle", "androidx-activity-compose"]
viewModel = ["viewmodel", "viewmodel-ktx"]
coroutines = ["coroutines-android"]
cameraX = ["camerax-core", "camerax-camera2", "camerax-extensions", "camerax-lifecycle"]
retrofit2 = ["retrofit", "retrofit-converter-gson", "okhttp-logging-interceptor"]
workManager = ["workmanager"]
instrumental-test = ["instrumental-espresso", "instrumental-test-runner", "instrumental-test-core", "instrumental-junit-ktx", "instrumental-test-rules"]
room = ["room-runtime", "room-ktx"]
appcompat = ["appcompat", "appcompat-resources"]
